# .github/workflows/build-heroku-app.yml // Just a comment
name: Build App on Heroku
on:
  push:
    branches:
      - atividade-02

jobs:
  heroku-pull-request:
    runs-on: ubuntu-latest
    env:
      HEROKU_APP_NAME: filmes-hugo // name of app on heroku

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }} // Heroku email address
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }} // Heroku API key
          heroku_app_name: ${{ env.HEROKU_APP_NAME }} // Declared above
          justlogin: true
          appdir: "filmes"

      - name: Add Heroku remote
        run: git remote

     