     
        
name: Staging deployment

on:
  push:
    branches:
      - atividade-02

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add api remote origin
        run: git remote add heroku-api https://heroku:30e21e7b-a4cb-450f-affe-aa848b41920d@git.heroku.com/filmes-hugo.git
      - name: Deploy api to Heroku
        run: git subtree push --prefix filmes heroku-api master
        
        
        